// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: task_info.proto

#include "task_info.pb.h"
#include "task_info.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace pai {
namespace pouw {
namespace task_info {

static const char* TaskInfo_method_names[] = {
  "/pai.pouw.task_info.TaskInfo/GetWaitingTasks",
};

std::unique_ptr< TaskInfo::Stub> TaskInfo::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< TaskInfo::Stub> stub(new TaskInfo::Stub(channel));
  return stub;
}

TaskInfo::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_GetWaitingTasks_(TaskInfo_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status TaskInfo::Stub::GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::pai::pouw::task_info::TaskListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_GetWaitingTasks_, context, request, response);
}

void TaskInfo::Stub::experimental_async::GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetWaitingTasks_, context, request, response, std::move(f));
}

void TaskInfo::Stub::experimental_async::GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_GetWaitingTasks_, context, request, response, std::move(f));
}

void TaskInfo::Stub::experimental_async::GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetWaitingTasks_, context, request, response, reactor);
}

void TaskInfo::Stub::experimental_async::GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_GetWaitingTasks_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>* TaskInfo::Stub::AsyncGetWaitingTasksRaw(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::pai::pouw::task_info::TaskListResponse>::Create(channel_.get(), cq, rpcmethod_GetWaitingTasks_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>* TaskInfo::Stub::PrepareAsyncGetWaitingTasksRaw(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::pai::pouw::task_info::TaskListResponse>::Create(channel_.get(), cq, rpcmethod_GetWaitingTasks_, context, request, false);
}

TaskInfo::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      TaskInfo_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< TaskInfo::Service, ::pai::pouw::task_info::TaskListRequest, ::pai::pouw::task_info::TaskListResponse>(
          [](TaskInfo::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::pai::pouw::task_info::TaskListRequest* req,
             ::pai::pouw::task_info::TaskListResponse* resp) {
               return service->GetWaitingTasks(ctx, req, resp);
             }, this)));
}

TaskInfo::Service::~Service() {
}

::grpc::Status TaskInfo::Service::GetWaitingTasks(::grpc::ServerContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace pai
}  // namespace pouw
}  // namespace task_info

