// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: task_info.proto
#ifndef GRPC_task_5finfo_2eproto__INCLUDED
#define GRPC_task_5finfo_2eproto__INCLUDED

#include "task_info.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace pai {
namespace pouw {
namespace task_info {

class TaskInfo final {
 public:
  static constexpr char const* service_full_name() {
    return "pai.pouw.task_info.TaskInfo";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::pai::pouw::task_info::TaskListResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::task_info::TaskListResponse>> AsyncGetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::task_info::TaskListResponse>>(AsyncGetWaitingTasksRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::task_info::TaskListResponse>> PrepareAsyncGetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::task_info::TaskListResponse>>(PrepareAsyncGetWaitingTasksRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::task_info::TaskListResponse>* AsyncGetWaitingTasksRaw(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::task_info::TaskListResponse>* PrepareAsyncGetWaitingTasksRaw(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::pai::pouw::task_info::TaskListResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>> AsyncGetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>>(AsyncGetWaitingTasksRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>> PrepareAsyncGetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>>(PrepareAsyncGetWaitingTasksRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, std::function<void(::grpc::Status)>) override;
      void GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetWaitingTasks(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void GetWaitingTasks(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::pai::pouw::task_info::TaskListResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>* AsyncGetWaitingTasksRaw(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pai::pouw::task_info::TaskListResponse>* PrepareAsyncGetWaitingTasksRaw(::grpc::ClientContext* context, const ::pai::pouw::task_info::TaskListRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetWaitingTasks_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetWaitingTasks(::grpc::ServerContext* context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetWaitingTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetWaitingTasks() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetWaitingTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaitingTasks(::grpc::ServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWaitingTasks(::grpc::ServerContext* context, ::pai::pouw::task_info::TaskListRequest* request, ::grpc::ServerAsyncResponseWriter< ::pai::pouw::task_info::TaskListResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetWaitingTasks<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_GetWaitingTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_GetWaitingTasks() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::pai::pouw::task_info::TaskListRequest, ::pai::pouw::task_info::TaskListResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::pai::pouw::task_info::TaskListRequest* request, ::pai::pouw::task_info::TaskListResponse* response) { return this->GetWaitingTasks(context, request, response); }));}
    void SetMessageAllocatorFor_GetWaitingTasks(
        ::grpc::experimental::MessageAllocator< ::pai::pouw::task_info::TaskListRequest, ::pai::pouw::task_info::TaskListResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::pai::pouw::task_info::TaskListRequest, ::pai::pouw::task_info::TaskListResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_GetWaitingTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaitingTasks(::grpc::ServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetWaitingTasks(
      ::grpc::CallbackServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetWaitingTasks(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_GetWaitingTasks<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_GetWaitingTasks<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetWaitingTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetWaitingTasks() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetWaitingTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaitingTasks(::grpc::ServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetWaitingTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetWaitingTasks() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetWaitingTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaitingTasks(::grpc::ServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetWaitingTasks(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_GetWaitingTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_GetWaitingTasks() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetWaitingTasks(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_GetWaitingTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetWaitingTasks(::grpc::ServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* GetWaitingTasks(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* GetWaitingTasks(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetWaitingTasks : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetWaitingTasks() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::pai::pouw::task_info::TaskListRequest, ::pai::pouw::task_info::TaskListResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::pai::pouw::task_info::TaskListRequest, ::pai::pouw::task_info::TaskListResponse>* streamer) {
                       return this->StreamedGetWaitingTasks(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetWaitingTasks() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetWaitingTasks(::grpc::ServerContext* /*context*/, const ::pai::pouw::task_info::TaskListRequest* /*request*/, ::pai::pouw::task_info::TaskListResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetWaitingTasks(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pai::pouw::task_info::TaskListRequest,::pai::pouw::task_info::TaskListResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetWaitingTasks<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetWaitingTasks<Service > StreamedService;
};

}  // namespace task_info
}  // namespace pouw
}  // namespace pai


#endif  // GRPC_task_5finfo_2eproto__INCLUDED
