.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. paicoin_qt test_paicoin_qt
clean: FORCE
	$(MAKE) -C .. paicoin_qt_clean test_paicoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_paicoin_qt_check
paicoin-qt paicoin-qt.exe: FORCE
	 $(MAKE) -C .. paicoin_qt
