.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. paiup test_paiup
clean: FORCE
	$(MAKE) -C .. paiup_clean test_paiup_clean
check: FORCE
	$(MAKE) -C .. test_paiup_check
paiup paiup.exe: FORCE
	 $(MAKE) -C .. paiup