// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: verifier.proto
#ifndef GRPC_verifier_2eproto__INCLUDED
#define GRPC_verifier_2eproto__INCLUDED

#include "verifier.pb.h"

#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace pai {
namespace pouw {
namespace verification {

// definition of verifier service
class Verifier final {
 public:
  static constexpr char const* service_full_name() {
    return "pai.pouw.verification.Verifier";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Verify(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::pai::pouw::verification::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::verification::Response>> AsyncVerify(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::verification::Response>>(AsyncVerifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::verification::Response>> PrepareAsyncVerify(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::verification::Response>>(PrepareAsyncVerifyRaw(context, request, cq));
    }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::verification::Response>* AsyncVerifyRaw(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::pai::pouw::verification::Response>* PrepareAsyncVerifyRaw(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Verify(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::pai::pouw::verification::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::verification::Response>> AsyncVerify(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::verification::Response>>(AsyncVerifyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::verification::Response>> PrepareAsyncVerify(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::pai::pouw::verification::Response>>(PrepareAsyncVerifyRaw(context, request, cq));
    }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    ::grpc::ClientAsyncResponseReader< ::pai::pouw::verification::Response>* AsyncVerifyRaw(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::pai::pouw::verification::Response>* PrepareAsyncVerifyRaw(::grpc::ClientContext* context, const ::pai::pouw::verification::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Verify_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Verify(::grpc::ServerContext* context, const ::pai::pouw::verification::Request* request, ::pai::pouw::verification::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Verify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Verify() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Verify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Verify(::grpc::ServerContext* context, const ::pai::pouw::verification::Request* request, ::pai::pouw::verification::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerify(::grpc::ServerContext* context, ::pai::pouw::verification::Request* request, ::grpc::ServerAsyncResponseWriter< ::pai::pouw::verification::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Verify<Service > AsyncService;
  template <class BaseClass>
  class WithGenericMethod_Verify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Verify() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Verify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Verify(::grpc::ServerContext* context, const ::pai::pouw::verification::Request* request, ::pai::pouw::verification::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Verify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Verify() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Verify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Verify(::grpc::ServerContext* context, const ::pai::pouw::verification::Request* request, ::pai::pouw::verification::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestVerify(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Verify : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Verify() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::pai::pouw::verification::Request, ::pai::pouw::verification::Response>(std::bind(&WithStreamedUnaryMethod_Verify<BaseClass>::StreamedVerify, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Verify() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Verify(::grpc::ServerContext* context, const ::pai::pouw::verification::Request* request, ::pai::pouw::verification::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedVerify(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::pai::pouw::verification::Request,::pai::pouw::verification::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Verify<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Verify<Service > StreamedService;
};

}  // namespace verification
}  // namespace pouw
}  // namespace pai


#endif  // GRPC_verifier_2eproto__INCLUDED
