// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: verifier.proto

#ifndef PROTOBUF_INCLUDED_verifier_2eproto
#define PROTOBUF_INCLUDED_verifier_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_verifier_2eproto 

namespace protobuf_verifier_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_verifier_2eproto
namespace pai {
namespace pouw {
namespace verification {
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
}  // namespace verification
}  // namespace pouw
}  // namespace pai
namespace google {
namespace protobuf {
template<> ::pai::pouw::verification::Request* Arena::CreateMaybeMessage<::pai::pouw::verification::Request>(Arena*);
template<> ::pai::pouw::verification::Response* Arena::CreateMaybeMessage<::pai::pouw::verification::Response>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace pai {
namespace pouw {
namespace verification {

enum Response_ReturnCode {
  Response_ReturnCode_GENERAL_ERROR = 0,
  Response_ReturnCode_OK = 200,
  Response_ReturnCode_BAD_REQUEST = 400,
  Response_ReturnCode_NOT_FOUND = 404,
  Response_ReturnCode_INVALID = 422,
  Response_ReturnCode_Response_ReturnCode_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Response_ReturnCode_Response_ReturnCode_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Response_ReturnCode_IsValid(int value);
const Response_ReturnCode Response_ReturnCode_ReturnCode_MIN = Response_ReturnCode_GENERAL_ERROR;
const Response_ReturnCode Response_ReturnCode_ReturnCode_MAX = Response_ReturnCode_INVALID;
const int Response_ReturnCode_ReturnCode_ARRAYSIZE = Response_ReturnCode_ReturnCode_MAX + 1;

const ::google::protobuf::EnumDescriptor* Response_ReturnCode_descriptor();
inline const ::std::string& Response_ReturnCode_Name(Response_ReturnCode value) {
  return ::google::protobuf::internal::NameOfEnum(
    Response_ReturnCode_descriptor(), value);
}
inline bool Response_ReturnCode_Parse(
    const ::std::string& name, Response_ReturnCode* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Response_ReturnCode>(
    Response_ReturnCode_descriptor(), name, value);
}
// ===================================================================

class Request : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pai.pouw.verification.Request) */ {
 public:
  Request();
  virtual ~Request();

  Request(const Request& from);

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(Request&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Request& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Request* other);
  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(NULL);
  }

  Request* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string msg_id = 1;
  void clear_msg_id();
  static const int kMsgIdFieldNumber = 1;
  const ::std::string& msg_id() const;
  void set_msg_id(const ::std::string& value);
  #if LANG_CXX11
  void set_msg_id(::std::string&& value);
  #endif
  void set_msg_id(const char* value);
  void set_msg_id(const char* value, size_t size);
  ::std::string* mutable_msg_id();
  ::std::string* release_msg_id();
  void set_allocated_msg_id(::std::string* msg_id);

  // string model_hash = 2;
  void clear_model_hash();
  static const int kModelHashFieldNumber = 2;
  const ::std::string& model_hash() const;
  void set_model_hash(const ::std::string& value);
  #if LANG_CXX11
  void set_model_hash(::std::string&& value);
  #endif
  void set_model_hash(const char* value);
  void set_model_hash(const char* value, size_t size);
  ::std::string* mutable_model_hash();
  ::std::string* release_model_hash();
  void set_allocated_model_hash(::std::string* model_hash);

  // string msg_next_id = 3;
  void clear_msg_next_id();
  static const int kMsgNextIdFieldNumber = 3;
  const ::std::string& msg_next_id() const;
  void set_msg_next_id(const ::std::string& value);
  #if LANG_CXX11
  void set_msg_next_id(::std::string&& value);
  #endif
  void set_msg_next_id(const char* value);
  void set_msg_next_id(const char* value, size_t size);
  ::std::string* mutable_msg_next_id();
  ::std::string* release_msg_next_id();
  void set_allocated_msg_next_id(::std::string* msg_next_id);

  // @@protoc_insertion_point(class_scope:pai.pouw.verification.Request)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr msg_id_;
  ::google::protobuf::internal::ArenaStringPtr model_hash_;
  ::google::protobuf::internal::ArenaStringPtr msg_next_id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_verifier_2eproto::TableStruct;
};
// -------------------------------------------------------------------

class Response : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pai.pouw.verification.Response) */ {
 public:
  Response();
  virtual ~Response();

  Response(const Response& from);

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(Response&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Response* other);
  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(NULL);
  }

  Response* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef Response_ReturnCode ReturnCode;
  static const ReturnCode GENERAL_ERROR =
    Response_ReturnCode_GENERAL_ERROR;
  static const ReturnCode OK =
    Response_ReturnCode_OK;
  static const ReturnCode BAD_REQUEST =
    Response_ReturnCode_BAD_REQUEST;
  static const ReturnCode NOT_FOUND =
    Response_ReturnCode_NOT_FOUND;
  static const ReturnCode INVALID =
    Response_ReturnCode_INVALID;
  static inline bool ReturnCode_IsValid(int value) {
    return Response_ReturnCode_IsValid(value);
  }
  static const ReturnCode ReturnCode_MIN =
    Response_ReturnCode_ReturnCode_MIN;
  static const ReturnCode ReturnCode_MAX =
    Response_ReturnCode_ReturnCode_MAX;
  static const int ReturnCode_ARRAYSIZE =
    Response_ReturnCode_ReturnCode_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  ReturnCode_descriptor() {
    return Response_ReturnCode_descriptor();
  }
  static inline const ::std::string& ReturnCode_Name(ReturnCode value) {
    return Response_ReturnCode_Name(value);
  }
  static inline bool ReturnCode_Parse(const ::std::string& name,
      ReturnCode* value) {
    return Response_ReturnCode_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // string description = 2;
  void clear_description();
  static const int kDescriptionFieldNumber = 2;
  const ::std::string& description() const;
  void set_description(const ::std::string& value);
  #if LANG_CXX11
  void set_description(::std::string&& value);
  #endif
  void set_description(const char* value);
  void set_description(const char* value, size_t size);
  ::std::string* mutable_description();
  ::std::string* release_description();
  void set_allocated_description(::std::string* description);

  // .pai.pouw.verification.Response.ReturnCode code = 1;
  void clear_code();
  static const int kCodeFieldNumber = 1;
  ::pai::pouw::verification::Response_ReturnCode code() const;
  void set_code(::pai::pouw::verification::Response_ReturnCode value);

  // @@protoc_insertion_point(class_scope:pai.pouw.verification.Response)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr description_;
  int code_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_verifier_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// string msg_id = 1;
inline void Request::clear_msg_id() {
  msg_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::msg_id() const {
  // @@protoc_insertion_point(field_get:pai.pouw.verification.Request.msg_id)
  return msg_id_.GetNoArena();
}
inline void Request::set_msg_id(const ::std::string& value) {
  
  msg_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pai.pouw.verification.Request.msg_id)
}
#if LANG_CXX11
inline void Request::set_msg_id(::std::string&& value) {
  
  msg_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pai.pouw.verification.Request.msg_id)
}
#endif
inline void Request::set_msg_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pai.pouw.verification.Request.msg_id)
}
inline void Request::set_msg_id(const char* value, size_t size) {
  
  msg_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pai.pouw.verification.Request.msg_id)
}
inline ::std::string* Request::mutable_msg_id() {
  
  // @@protoc_insertion_point(field_mutable:pai.pouw.verification.Request.msg_id)
  return msg_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_msg_id() {
  // @@protoc_insertion_point(field_release:pai.pouw.verification.Request.msg_id)
  
  return msg_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_msg_id(::std::string* msg_id) {
  if (msg_id != NULL) {
    
  } else {
    
  }
  msg_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg_id);
  // @@protoc_insertion_point(field_set_allocated:pai.pouw.verification.Request.msg_id)
}

// string model_hash = 2;
inline void Request::clear_model_hash() {
  model_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::model_hash() const {
  // @@protoc_insertion_point(field_get:pai.pouw.verification.Request.model_hash)
  return model_hash_.GetNoArena();
}
inline void Request::set_model_hash(const ::std::string& value) {
  
  model_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pai.pouw.verification.Request.model_hash)
}
#if LANG_CXX11
inline void Request::set_model_hash(::std::string&& value) {
  
  model_hash_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pai.pouw.verification.Request.model_hash)
}
#endif
inline void Request::set_model_hash(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  model_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pai.pouw.verification.Request.model_hash)
}
inline void Request::set_model_hash(const char* value, size_t size) {
  
  model_hash_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pai.pouw.verification.Request.model_hash)
}
inline ::std::string* Request::mutable_model_hash() {
  
  // @@protoc_insertion_point(field_mutable:pai.pouw.verification.Request.model_hash)
  return model_hash_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_model_hash() {
  // @@protoc_insertion_point(field_release:pai.pouw.verification.Request.model_hash)
  
  return model_hash_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_model_hash(::std::string* model_hash) {
  if (model_hash != NULL) {
    
  } else {
    
  }
  model_hash_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), model_hash);
  // @@protoc_insertion_point(field_set_allocated:pai.pouw.verification.Request.model_hash)
}

// string msg_next_id = 3;
inline void Request::clear_msg_next_id() {
  msg_next_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Request::msg_next_id() const {
  // @@protoc_insertion_point(field_get:pai.pouw.verification.Request.msg_next_id)
  return msg_next_id_.GetNoArena();
}
inline void Request::set_msg_next_id(const ::std::string& value) {
  
  msg_next_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pai.pouw.verification.Request.msg_next_id)
}
#if LANG_CXX11
inline void Request::set_msg_next_id(::std::string&& value) {
  
  msg_next_id_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pai.pouw.verification.Request.msg_next_id)
}
#endif
inline void Request::set_msg_next_id(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  msg_next_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pai.pouw.verification.Request.msg_next_id)
}
inline void Request::set_msg_next_id(const char* value, size_t size) {
  
  msg_next_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pai.pouw.verification.Request.msg_next_id)
}
inline ::std::string* Request::mutable_msg_next_id() {
  
  // @@protoc_insertion_point(field_mutable:pai.pouw.verification.Request.msg_next_id)
  return msg_next_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Request::release_msg_next_id() {
  // @@protoc_insertion_point(field_release:pai.pouw.verification.Request.msg_next_id)
  
  return msg_next_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Request::set_allocated_msg_next_id(::std::string* msg_next_id) {
  if (msg_next_id != NULL) {
    
  } else {
    
  }
  msg_next_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msg_next_id);
  // @@protoc_insertion_point(field_set_allocated:pai.pouw.verification.Request.msg_next_id)
}

// -------------------------------------------------------------------

// Response

// .pai.pouw.verification.Response.ReturnCode code = 1;
inline void Response::clear_code() {
  code_ = 0;
}
inline ::pai::pouw::verification::Response_ReturnCode Response::code() const {
  // @@protoc_insertion_point(field_get:pai.pouw.verification.Response.code)
  return static_cast< ::pai::pouw::verification::Response_ReturnCode >(code_);
}
inline void Response::set_code(::pai::pouw::verification::Response_ReturnCode value) {
  
  code_ = value;
  // @@protoc_insertion_point(field_set:pai.pouw.verification.Response.code)
}

// string description = 2;
inline void Response::clear_description() {
  description_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Response::description() const {
  // @@protoc_insertion_point(field_get:pai.pouw.verification.Response.description)
  return description_.GetNoArena();
}
inline void Response::set_description(const ::std::string& value) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:pai.pouw.verification.Response.description)
}
#if LANG_CXX11
inline void Response::set_description(::std::string&& value) {
  
  description_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:pai.pouw.verification.Response.description)
}
#endif
inline void Response::set_description(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:pai.pouw.verification.Response.description)
}
inline void Response::set_description(const char* value, size_t size) {
  
  description_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:pai.pouw.verification.Response.description)
}
inline ::std::string* Response::mutable_description() {
  
  // @@protoc_insertion_point(field_mutable:pai.pouw.verification.Response.description)
  return description_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Response::release_description() {
  // @@protoc_insertion_point(field_release:pai.pouw.verification.Response.description)
  
  return description_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Response::set_allocated_description(::std::string* description) {
  if (description != NULL) {
    
  } else {
    
  }
  description_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), description);
  // @@protoc_insertion_point(field_set_allocated:pai.pouw.verification.Response.description)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace verification
}  // namespace pouw
}  // namespace pai

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::pai::pouw::verification::Response_ReturnCode> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pai::pouw::verification::Response_ReturnCode>() {
  return ::pai::pouw::verification::Response_ReturnCode_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_verifier_2eproto
